project:
  type: website
  output-dir: docs

execute: 
  freeze: auto

website:
  title: "Cédric Vidonne"
  description: "Information Management Officer at UNHCR specialized in data visualization and mapping."
  # favicon: 
  site-url: "https://vidonne.github.io/"
  repo-url: "https://github.com/vidonne/vidonne.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true



